### ISSUE TITLE
build failure on ghc 8.0

### ISSUE THREAD

**Issue by cartazio** [blamario/monoid-subclasses#11]
4 of 9] Compiling Data.Monoid.Textual ( Data/Monoid/Textual.hs, dist/build/Data/Monoid/Textual.o )

Data/Monoid/Textual.hs:354:15: error:
    The INLINE pragma for ‘split’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘split’ is declared)

Data/Monoid/Textual.hs:537:15: error:
    The INLINE pragma for ‘fromText’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘fromText’ is declared)

Data/Monoid/Textual.hs:539:15: error:
    The INLINE pragma for ‘mapAccumL’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘mapAccumL’ is declared)

Data/Monoid/Textual.hs:540:15: error:
    The INLINE pragma for ‘mapAccumR’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘mapAccumR’ is declared)

Data/Monoid/Textual.hs:549:15: error:
    The INLINE pragma for ‘split’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘split’ is declared)

Data/Monoid/Textual.hs:611:15: error:
    The INLINE pragma for ‘fromText’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘fromText’ is declared)

Data/Monoid/Textual.hs:623:15: error:
    The INLINE pragma for ‘split’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘split’ is declared)

**Comment by blamario** [comment]
Thank you for the alert. Fixed by https://github.com/blamario/monoid-subclasses/commit/8b1e9111a3505bddd394a182ff7d2c29efc4b04a
