### ISSUE TITLE
incompatible with ghc 8.6

### ISSUE THREAD

**Issue by clinty** [blamario/monoid-subclasses#17]
Please raise the upper bound on containers.

Contributes to https://github.com/commercialhaskell/stackage/issues/4008

**Comment by qrilka** [comment]
Looks to be fixed already

**Comment by blamario** [comment]
Indeed, I forgot to close it after https://github.com/blamario/monoid-subclasses/commit/020f192702146aa4315265af70bcb60373893671

Thanks.
