### ISSUE TITLE
Awkward performance requirements in class laws

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#20]
The performance requirements often mention a notion of `length` even though the class itself doesn't even guarantee that the concept of a `length` exists at all.

Personally I think performance requirements should be kept out of the laws, and that they should solely focus on equalities / totality.

**Comment by blamario** [comment]
I agree they're awkward. The idea was to provide some minimal performance guarantees to the typeclass clients, so they'd know that if an instance exists it's also usable.

I may end up dropping the requirement, but I'll have to think about it.

**Comment by blamario** [comment]
Fixed by https://github.com/blamario/monoid-subclasses/commit/7136bb6aa06da356b42d991c54b193927d09b43d
