### ISSUE TITLE
Add `Monus` (And `Left`/`Right` variants) class.

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#21]
Currently it seems like I can't do traditional Set subtraction with any of these classes, [monus](https://en.wikipedia.org/wiki/Monus) appears to be a monoidal generalization of this concept.

It should probably be a subclass of `ReductiveMonoid` as given a hypothetical `monus :: Monus m => m -> m -> m`, you could implement `</>` as `a </> b = let c = monus a b in bool Nothing c (b <> c == a)`. However it should not be a subclass of `Cancellative` as `Set` is an example of a `Monus` that isn't `Cancellative`.

**Comment by blamario** [comment]
I wasn't aware of that concept, thanks! Would you be willing to prepare a PR?

**Comment by blamario** [comment]
I started looking into dropping the commutative requirement.

> if for each pair of elements *a* and *b*, a unique smallest element *c* exists such that *a ≤ b + c* , then M is called a commutative monoid with monus and the monus *a ∸ b* of any two elements *a*  and *b* can be defined as this unique smallest element *c* such that *a ≤ b + c*.

Replace ≤ in this definition by *isPrefixOf*, then we get

if for each pair of elements *a* and *b*, a unique smallest element *c* exists such that `isPrefixOf a (c <> b)`, then M is called a -commutative- monoid with _left_ monus...

The *unique smallest element* would mean that *c* `isPrefixOf` any `d` such that `isPrefixOf a (d <> b)`. For strings, some examples would be

    "abc" ∸ "c" = "ab"
    "abc" ∸ "d" = "abc"
    "abc" ∸ "ab" = "abc"

In this case it's clear that `a ∸ b = fromMaybe a (stripSuffix b a)`, and that may be the general definition. It certainly works as your set difference. I'll have to look into it some more.

**Comment by tysonzero** [comment]
So the issue is that:

```
a ∸ b = fromMaybe a (stripSuffix b a)
```

Is almost but not quite what you want, when `stripSuffix` is `Nothing` you can only sometimes just return `a`:

```
"abc" `stripSuffix` "cd" = Nothing
"abc" ∸ "cd" = "ab"

[1, 2, 3] `stripSuffix` [3, 4, 5] = Nothing
[1, 2, 3] ∸ [3, 4, 5] = [1, 2]
```

**Comment by blamario** [comment]
You're quite correct.

Do you have any naming suggestion for the non-commutative variants of the operation? You'll note that the existing `stripPrefix`, `commonPrefix`, and other operations are named to be immediately understandable in the context of sequences. The names are also not wrong in a more general context, because the prefix in question can be thought of as in the operation `(prefix <>)`. It would be nice to preserve these two properties, but I'm coming up blank.

**Comment by tysonzero** [comment]
I can't really think of anything better than just `leftMonus`, `monus` and `rightMonus` to be honest. I think the most useful use-cases will be the commutative variant (Mostly sets, maybe naturals and bool variants as well).

**Comment by blamario** [comment]
The classes have been added by 5ecbb1e04100c8e5b8bb9c29157b5d66e959839a

I'm not happy with the formulation of the laws, but I couldn't come up with anything better. The preceding commit applies the same ordering treatment to GCD classes and removes the Product and Sum instances because they're not law-abiding any more. I'm planning to add the instances for `Sum Natural` and `Product Natural` instead.

I won't close the issue until I add the remaining instances (lists, Vector, ByteString, Text, ...), and that's going to take a while. Use the time to comment on the design, please.

**Comment by tysonzero** [comment]
`Monus` seems to be a concept fairly unique to this concept, so for brevity it's probably safe to shrink the class names down to `Monus`, `LeftMonus` and `RightMonus`.

Limiting `GCD` and `Factorial` stuff to non-negative types seems like a good idea. Ideally a NonNegative subclass of Integral of some sort instead of having to implement types case by case.

My biggest skepticism with the current implementation is that the laws for `MonoidWithLeftMonus` reference `isSuffixOf` from `RightReductiveMonoid`, which is NOT a superclass. So essentially if you don't implement that class the laws don't exist.

I will try and come up with a good set of laws for `(Left|Right|)Monus` soon.

**Comment by blamario** [comment]
Contrary to my intuition, `Map` and `IntMap` have `RightMonus` but no `LeftMonus` instances. The implication is that `MonoidWithRightMonus` is a subclass of `LeftReductiveMonoid`. And the mirror image of course. This change (https://github.com/blamario/monoid-subclasses/commit/651a1d96f2fc6971133894d98d07ef8e10295156) also takes care of the problem with the laws.

**Comment by tysonzero** [comment]
So `Map` and `IntMap` actually do have valid `LeftMonus` and `RightReductiveMonoid` instances.

Specifically:

```
instance (Ord k, Eq v) => LeftReductiveMonoid (Map k v) where
    stripPrefix a b = bool Nothing (Just $ b `stripPrefixOverlap` a) (a `isPrefixOf` b)
    isPrefixOf a b = a <> stripPrefixOverlap a b == b
    -- isPrefixOf = Map.isSubmapOf

instance (Ord k, Eq v) => RightReductiveMonoid (Map k v) where
    stripSuffix a b = bool Nothing (Just $ stripSuffixOverlap a b) (a `isSuffixOf` b)
    isSuffixOf a b = stripSuffixOverlap a b <> a == b
    -- isSuffixOf a b = Map.keysSet a `Set.isSubsetOf` Map.keysSet b

instance Ord k => MonoidWithLeftMonus (Map k v) where
    stripPrefixOverlap = flip Map.difference

instance (Ord k, Eq v) => MonoidWithRightMonus (Map k v) where
    stripSuffixOverlap a b = Map.differenceWith (\x y -> if x == y then Nothing else Just x) b a
```

If we ignore the fact that some types lack `Eq` (mathematical all things have `Eq` in the form of observational identity) the above tells me the following.

`(Left|Right)Monus` needs `(Left|Right)Reductive` respectively as a superclass on the basis that the `(Left|Right)Reductive` instances above are valid for every `(Left|Right)Monus` and don't directly use any `Map` functionality.

I similarly think that some appropriate additional `(Left|Right)Monus` laws are that the `(Left|Right)Reductive` parent instances match the following.

`(Left|Right)Monus` should either have `(Right|Left)Reductive` respectively as a superclass for the sake of the laws.

However what complicates things is computability and `Eq`. Technically every `Monoid` is both `LeftReductive` and `RightReductive` in the mathematical sense, it's just that the right value to return from `strip***` might be ambiguous without a good canonical answer (in the above I always choose the "least" where `<>` is a increasing-ish function), and both `is***` and `strip***` might be uncomputable (e.g. `->` instance).

Given the `Eq` situation I will want to think some more about how I think it's best to approach this. But I do think the above instances are all pretty reasonable.

**Comment by blamario** [comment]
648df488 added the instances, 599731a folded the `(Left|Right)Monus` classes into `OverlappingGCDMonoid`. I may shorten `MonoidWithMonus` to `Monus`, I just have to think about the possibility of a monus on a non-monoidal semigroup.

**Comment by blamario** [comment]
All done as of 6e50a267f98dcd1663a6cfb5d33a63be3bd1eeb2
