### ISSUE TITLE
Consider adding `Right*` instances for `[a]`

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#23]
I'm assuming you omitted them for perf reasons, but when I'm dealing with short `String`'s or other `[a]`, which is not particularly rare, I really just want to be able to stripSuffix and similar with no hassle. Also time complexity wise the perf is no worse than `Text`.

**Comment by blamario** [comment]
Fixed by https://github.com/blamario/monoid-subclasses/commit/441f6a295b30ba40042307515d5efe6770280ba3
