### ISSUE TITLE
`instance Ord k => LeftReductiveMonoid (Map k a)` unlawful

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#24]
`stripPrefix` is too "forgetful" and therefore does not obey `maybe b (a <>) (stripPrefix a b) == b`.

```
a = [(0, 0)]
b = [(0, 1)]
stripPrefix a b = Just []
maybe b (a <>) (stripPrefix a b) = [(0, 0)]
[(0, 0)] /= [(0, 1)]
```

Unfortunately I think the existing `Monoid` instances of `Map` and `IntMap` have trapped you here. Ideally something like `instance (Ord k, LeftReductiveMonoid a) => LeftReductiveMonoid (Map k a)` could have worked, to basically mirror the `Maybe` instance.

**Comment by tysonzero** [comment]
There is actually a law abiding `RightReductiveMonoid` instance for `Map`, but you aren't going to love it.

Due to the left bias of `<>`:

**Comment by blamario** [comment]
> `stripPrefix` is too "forgetful" and therefore does not obey `maybe b (a <>) (stripPrefix a b) == b`

Good catch. This should have been caught by property tests, which means there is another bug lurking in the test suite. Another possible fix for the instance is to replace `Map.isSubmapOfBy (\_ _-> True)` by plain `Map.isSubmap`, but your suggestion to switch the instance to `RightReductiveMonoid` is also workable.

**Comment by tysonzero** [comment]
I was mostly joking with my suggestion as the instance wouldn't be very useful. But yes of course `Map.isSubmap` seems like a very reasonable approach given the current `Monoid (Map k a)` instance, and it would work for Left, Right and commutative variants.

**Comment by blamario** [comment]
Fixed using the `Map.isSubmap` approach. Sadly this still doesn't allow a `RightReductiveMonoid` instance due to the law that `isSuffixOf b (a <> b)`
