### ISSUE TITLE
`Factorial` laws too strong

### ISSUE THREAD

**Issue by tysonzero** [blamario/monoid-subclasses#31]
Specifically `Product Natural`, sets and maps don't obey the following laws:

```
factors . reverse == List.reverse . factors
primeSuffix s == primePrefix (reverse s)
```

It seems like those laws and `reverse` itself should most likely be moved to `StableFactorial`.

There are at least four categories of instance that I can see: list-like, set-like, map-like and bag-like (`Product Natural`). Each of them have various laws that apply to them but not necessarily the others.

**Comment by blamario** [comment]
Fixed, thanks for reporting.
