### ISSUE TITLE
`OverlappingGCDMonoid` instance for `Map` may be unlawful.

### ISSUE THREAD

**Issue by jonathanknowles** [blamario/monoid-subclasses#36]
Hi @blamario 

I was writing some QuickCheck properties for instances of [`OverlappingGCDMonoid`](https://hackage.haskell.org/package/monoid-subclasses-1.1.3/docs/Data-Monoid-GCD.html#t:OverlappingGCDMonoid), and I discovered a counterexample for `Map` that does not appear to satisfy the laws for this class.

I'm testing the following laws (quoted from the [documentation](https://hackage.haskell.org/package/monoid-subclasses-1.1.3/docs/Data-Monoid-GCD.html#t:OverlappingGCDMonoid)):
```hs
stripOverlap a b == (stripSuffixOverlap b a, overlap a b, stripPrefixOverlap a b)
stripSuffixOverlap b a <> overlap a b == a
overlap a b <> stripPrefixOverlap a b == b
```

Here's a minimal counterexample, where two out the three laws are not satisfied:
```hs
> import Data.Monoid.GCD
> import qualified Data.Map.Strict as Map
> a = Map.fromList [(0 :: Int, 0 :: Int)]
> b = Map.fromList [(0 :: Int, 1 :: Int)]
> stripOverlap a b == (stripSuffixOverlap b a, overlap a b, stripPrefixOverlap a b)
False
> stripSuffixOverlap b a <> overlap a b == a
True
> overlap a b <> stripPrefixOverlap a b == b
False
```

Comparing the [definition of the instance for `Map`](https://hackage.haskell.org/package/monoid-subclasses-1.1.3/docs/src/Data.Monoid.Monus.html#line-243) with the [documentation for `OverlappingGCDMonoid`](https://hackage.haskell.org/package/monoid-subclasses-1.1.3/docs/Data-Monoid-GCD.html#t:OverlappingGCDMonoid), I noticed that the positions of `stripSuffixOverlap` and `stripPrefixOverlap` have been transposed:

```hs
stripOverlap a b == (stripSuffixOverlap b a, overlap a b, stripPrefixOverlap a b)
stripOverlap a b =  (stripPrefixOverlap b a, overlap a b, stripSuffixOverlap a b)
```
However, even if we were to fix the implementation by reversing the transposition, the following law would still not hold:

```hs
> a = Map.fromList [(0 :: Int, 0 :: Int)]
> b = Map.fromList [(0 :: Int, 1 :: Int)]
> overlap a b <> stripPrefixOverlap a b == b
False
```

I have tried to write a lawful instance for `Map`, but I'm not yet sure whether it's possible due to the behaviour of `<>` for `Map` (among other things).

Though perhaps I've missed something?

By the way, many thanks for writing this library!

**Comment by blamario** [comment]
Thanks for reporting this! I'm baffled that the test suite is missing the tests of documented laws. I'll start there.

**Comment by blamario** [comment]
The stupid `instance Semigroup Map` is going to be the death of me one day, I know. But not today. Thanks again!
