### ISSUE TITLE
Suspected unlawful `Monus` instance for `Maybe`.

### ISSUE THREAD

**Issue by jonathanknowles** [blamario/monoid-subclasses#38]
Hi @blamario 

I think I've discovered a counterexample to the `Monus` laws for `Maybe`.

I tested against the latest version of `monoid-subclasses` in this repository: 9255072c640f590c92c9ebc9ddc153555501dad7

## Counterexample

First some imports:
```hs
> import Data.Monoid (Sum (Sum))
> import Data.Monoid.GCD (OverlappingGCDMonoid (..))
> import Data.Monoid.Monus (Monus (..))
> import Numeric.Natural (Natural)
```

Then define the counterexample arguments:
```hs
> a = Just (Sum (0 :: Natural))
> b = Just (Sum (0 :: Natural))
```

The laws stated in the documentation are as follows ([source](https://hackage.haskell.org/package/monoid-subclasses-1.2/docs/Data-Monoid-Monus.html#t:Monus)):
- `(<\>) = flip stripPrefixOverlap`
- `(<\>) = flip stripSuffixOverlap`

When we test these laws with the example arguments, it seems that the laws are not satisfied:
```hs
> (<\>) a b == flip stripPrefixOverlap a b
False
> (<\>) a b == flip stripSuffixOverlap a b
False
```

If we evaluate just the LHS, we get:
```hs
> (<\>) a b
Just (Sum {getSum = 0})
```

If we evaluate just the RHS, we get:
```hs
> flip stripPrefixOverlap a b
Nothing
> flip stripSuffixOverlap a b
Nothing
```

Perhaps I've interpreted the laws incorrectly?

Many thanks!

Jonathan

**Comment by jonathanknowles** [comment]
This might actually be a problem with the `Monus` instance for `Maybe`.

I can also reproduce the issue when testing with values of `Maybe ()`:

```hs
> a = Just ()
> b = Just ()
> (<\>) a b == flip stripPrefixOverlap a b
False
> (<\>) a b == flip stripSuffixOverlap a b
False
> (<\>) a b
Just ()
> flip stripPrefixOverlap a b
Nothing
> flip stripSuffixOverlap a b
Nothing
```

**Comment by jonathanknowles** [comment]
I believe I've found a fix for this issue here https://github.com/blamario/monoid-subclasses/pull/39.

**Comment by blamario** [comment]
Fixed by @jonathanknowles
