### ISSUE TITLE
monoid-subclasses-0.4.0.3 test suite failure

### ISSUE THREAD

**Issue by peti** [blamario/monoid-subclasses#4]
Citing from http://hydra.nixos.org/build/19277425/nixlog/2/raw:

    Textual.foldl':               FAIL (0.36s)
      *** Failed! Falsifiable (after 73 tests): 
      "?\[137].\[138,158]<xT\[142]!x5ª\14^_\[162,173]-\[156]\[223]<s\[219]\[227]\[254]\[240,182]`\[254]\[233]\[243]\[208]\[249]\18\5\[248]\[230]\[244]\12\15Ld<\[240,147,154,162]H"
      Use --quickcheck-replay '72 TFGenR 2ABAADACF782BEC9F280B33CC904F800B137F1A77391A8DDF195E5BA950B6885 0 8796093022207 43 0' to reproduce.

**Comment by blamario** [comment]
Thank you for the report. Fixed by revision cb555da.
