### ISSUE TITLE
`LCMMonoid` type class

### ISSUE THREAD

**Issue by jonathanknowles** [blamario/monoid-subclasses#42]
Hi @blamario 

I'm writing a set of libraries to work with monoidal structures (including [total-monoidal-maps](https://github.com/jonathanknowles/total-monoidal-maps), which is not yet released).

I'd love to be able provide a generalised `lcm` method for commutative monoids that admit an LCM, similar to the existing `gcd` method of `GCDMonoid`.

Would you be open to me creating a PR that adds an `LCMMonoid` type class to `monoid-subclasses`? (I actually already have a [unpolished prototype](https://github.com/blamario/monoid-subclasses/compare/master...jonathanknowles:monoid-subclasses:jonathanknowles/lcm-monoid?expand=1): I'd be happy to turn it into a more polished PR with documentation, instances and tests, provided you think it's a good idea?)

## Proposal

Assuming a minimal set of superclass dependencies, we might define `LCMMonoid` as:

```hs
class (Monoid m, Reductive m) => LCMMonoid m where
    lcm :: m -> m -> m
```

Where `lcm` would satisfy the laws we might expect from LCM:

```hs
-- Identity
lcm a mempty == a
lcm mempty a == a

-- Idempotence
lcm a a == a

-- Commutativity
lcm a b == lcm b a

-- Associativity
lcm (lcm a b) c == lcm a (lcm b c)

-- Distributivity
lcm (a <> b) (a <> c) == a <> lcm b c
lcm (a <> c) (b <> c) == lcm a b <> c

-- Reductivity
isJust (lcm a b </> a)
isJust (lcm a b </> b)

-- Uniqueness
all isJust [c </> a, c </> b, lcm a b </> c] ==> lcm a b == c
```

## Justification

Given certain typeclass constraints, it is already possible to compute an LCM. For example:

 - With `GCDMonoid` and `Monus`:
   ```hs
   lcm a b = (a <\> b) <> gcd a b <> (b <\> a)
   ```
 - With `Commutative` and `OverlappingGCDMonoid`:
   ```hs
   lcm a b = stripSuffixOverlap b a <> overlap a b <> stripPrefixOverlap a b
   ```

However, for some types, we can provide a more direct (and potentially more efficient) implementation. For example:

```hs
instance LCMMonoid (Product Natural) where
    lcm (Product a) (Product b) = Product (Prelude.lcm a b)

instance LCMMonoid (Sum Natural) where
    lcm (Sum a) (Sum b) = Sum (Prelude.max a b)

instance Ord a => LCMMonoid (Set a) where
    lcm = Set.union
    
instance Ord a => LCMMonoid (IntSet a) where
    lcm = IntSet.union
```

### Provide `LCMMonoid` in a separate library

If you'd prefer not to include `LCMMonoid` within `monoid-subclasses`, I would be happy to publish this class in a separate library that extends `monoid-subclasses`.

### Go further, and provide a richer tapestry of superclasses

Similar to the `GCDMonoid` type class (which has three superclasses), I can imagine an analogous set of superclasses for `LCMMonoid`, including:

```hs
class (Monoid m, LeftReductive m) => LeftLCMMonoid m where
    leftLCM :: m -> m -> m

class (Monoid m, RightReductive m) => RightLCMMonoid m where
    rightLCM :: m -> m -> m
```
These might have analogous laws to `LCMMonoid`, but defined in terms of `LeftReductive` and `RightReductive` instead of `Reductive`.

And similar to `OverlappingGCDMonoid`, we might imagine an `OverlappingLCMMonoid` class:

```hs
class (Monoid m, LeftReductive m, RightReductive m) => OverlappingLCMMonoid where
    overlapLCM :: m -> m -> m

    -- Just for illustration, could be provided by a newtype and separate instance:
    default overlapLCM :: OverlappingGCDMonoid m => m -> m -> m
    overlapLCM a b =
        stripSuffixOverlap b a <> overlap a b <> stripPrefixOverlap a b
```

However, after reading through as much research literature as I could find about left- and right-LCMs, it's still not clear to me how useful non-Abelian LCM operations are in practice, especially for data structures we encounter in the "real world". (In particular, for string-like and list-like types, not all pairs of values admit a left-LCM or right-LCM, so attempting to extend this hypothetical hierarchy to such types might require `leftLCM` and `rightLCM` to have type `m -> m -> Maybe m`, which would break symmetry with the `GCDMonoid` family.) Though perhaps I've missed something?

Anyway, I'd love to hear your thoughts on the proposal to simply add a `LCMMonoid` class as a subclass of `Monoid` and `Reductive`. I'd be happy to create a PR if you like.

Thanks for reading!

**Comment by blamario** [comment]
You have obviously thought this through quite thoroughly. I have no objection to your proposal. It's sad that GCD and LCM operations are not equally graceful when it comes to non-Abelian monoids, but such is life and math. The only suggestion I have is to consider making `GCDMonoid` a superclass of `LCMMonoid`. Perhaps you have considered it and decided against, in which case I can't really muster an argument in its defence. Either way, the PR is welcome.

**Comment by jonathanknowles** [comment]
Hi @blamario 

> The only suggestion I have is to consider making `GCDMonoid` a superclass of `LCMMonoid`.

I really like this suggestion, because it allows us to also express the absorption and distributivity relationships for `lcm` and `gcd` as part of the class specification for `LCMMonoid`:

```hs
# Absorption
lcm a (gcd a b) == a
gcd a (lcm a b) == a 

# Distributivity
lcm a (gcd b c) == gcd (lcm a b) (lcm a c)
gcd a (lcm b c) == lcm (gcd a b) (gcd a c)
```

I'll create a PR that makes `LCMMonoid` into a subclass of `GCDMonoid`, as you suggest.

(The alternative would be to say something like: "If `m` is also an instance of `GCDMonoid`, then the following additional laws must be satisfied". Though this alternative seems less satisfactory.)

**Comment by jonathanknowles** [comment]
Hi @blamario 

As promised, https://github.com/blamario/monoid-subclasses/pull/43 adds the `LCMMonoid` type class, together with tests and documentation.

To the greatest extent possible, I've aimed to mimic your original style for documentation and code formatting. Though if I've got anything wrong, and you need me to make any changes, let me know! Would be happy to do so.

In addition:
- In downstream branch [**`quickcheck-monoid-subclasses:lcm-monoid`**](https://github.com/jonathanknowles/quickcheck-monoid-subclasses/compare/main...jonathanknowles/lcm-monoid):
    - I've prepared a new [`Laws`](https://hackage.haskell.org/package/quickcheck-classes-0.6.5.0/docs/Test-QuickCheck-Classes.html#t:Laws) definition for `LCMMonoid` that can be added to the [`quickcheck-monoid-subclasses`](https://hackage.haskell.org/package/quickcheck-monoid-subclasses) package.
    - (I created this package in order to give people a simple way to test that their `monoid-subclasses` instances are lawful. I hope that someone will find it useful!)
- In downstream branch [**`total-monoidal-maps:lcm`**](https://github.com/jonathanknowles/total-monoidal-maps/compare/main...jonathanknowles/lcm):
    - I've added an `LCMMonoid` instance for the `MonoidMap` data type.
    - I've tested this instance with the above newly-created `Laws` definition, with several different monoidal value types.
    
Many thanks for considering this PR!

Best wishes

Jonathan

**Comment by blamario** [comment]
Thank you for the contribution!

**Comment by jonathanknowles** [comment]
> Thank you for the contribution!

Any time. Thanks for accepting it!
