### ISSUE TITLE
Distributivity laws for `GCDMonoid`

### ISSUE THREAD

**Issue by jonathanknowles** [blamario/monoid-subclasses#47]
Hi @blamario 

While reading through the documentation for `GCDMonoid`, I noticed this statement about distributivity laws:

> If a `GCDMonoid` happens to also be `Cancellative`, it should additionally satisfy the following laws:
> ```hs
> gcd (a <> b) (a <> c) == a <> gcd b c
> gcd (a <> c) (b <> c) == gcd a b <> c
> ```

This got me thinking: **_must_ a GCD monoid be cancellative in order to satisfy the above laws**?

Among the types for which instances of `GCDMonoid` are provided, only the following types are not `Cancellative`:

- `IntSet`
- `Set a`
- `Product Natural`

But despite non-cancellativity, these types **_do_** seem to satisfy the distributivity laws:

---

### Set types

We can consider the `IntSet` and `Set a` types together, as their `GCDMonoid` and `Semigroup` instances are defined equivalently:

```hs
instance Semigroup IntSet  where (<>) = IntSet.union
instance Semigroup (Set a) where (<>) =    Set.union

instance GCDMonoid IntSet  where gcd = IntSet.intersection
instance GCDMonoid (Set a) where gcd =    Set.intersection
```

Of course, these types are certainly not `Cancellative`:

```hs
-- In order to be `Cancellative`, we must have:
(a <> b) </> b == Just a

-- If:
a = Set.fromList [0]
b = Set.fromList [0]

-- Then:
(a <> b)       ==       Set.fromList [0]
(a <> b) </> b == Just (Set.fromList [ ])
Just a         == Just (Set.fromList [0])

-- But:
Just (Set.fromList []) /= Just (Set.fromList [0])
```

However, we can show that they satisfy the distributivity laws.

If we substitute the above instance method definitions into the distributivity laws, we obtain:
```hs
intersection (union a b) (union a c) == union a (intersection b c)
intersection (union a c) (union b c) == union (intersection a b) c
```

Rewriting with traditional set notation, we obtain:
```
(A ∪ B) ∩ (A ∪ C) = A ∪ (B ∩ C)
(A ∪ B) ∩ (B ∪ C) = (A ∩ B) ∪ C
```
These are equivalent to the standard distributivity law(s) for sets, which can be proven in a number of different ways.

---

### `Product Natural`

This type has the following `Semigroup` and `GCDMonoid` instances:
```hs
instance Semigroup (Product Natural) where (<>) = Prelude.(*)
instance GCDMonoid (Product Natural) where gcd  = Prelude.gcd
```

This type is also not `Cancellative`:
```hs
-- In order to be `Cancellative`, we must have:
(a <> b) </> b == Just a

-- If:
a = Product 1
b = Product 0

-- Then:         
(a <> b)       ==       Product 0
(a <> b) </> b == Just (Product 0)
Just a         == Just (Product 1)

-- But:
Just (Product 0) /= Just (Product 1)
```

But again, we can show that `Product Natural` satisfies the GCD distributivity laws.

If we substitute the instance method definitions above into the distributivity laws, we obtain:
```hs
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (a * c) (b * c) == Prelude.gcd a b * c
```

This is equivalent to the distributivity laws for the standard gcd function on non-zero natural numbers:
```
gcd (ab, ac) = a * gcd (b, c)
gcd (ac, bc) = gcd (a, b) * c
```

But what about values of `Product 0`? Well it turns out that the laws still hold for zero values, since `Prelude.gcd` is defined such that:
```hs
Prelude.gcd 0 a == a
Prelude.gcd a 0 == a
```

Which means that:
```hs
-- When a = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (0 * b) (0 * c) == 0 * Prelude.gcd b c
Prelude.gcd  0       0      == 0
                     0      == 0 -- True

-- When b = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (a * 0) (a * c) == a * Prelude.gcd 0 c
Prelude.gcd      0  (a * c) == a *               c
                     a * c  == a *               c -- True

-- When c = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (a * b) (a * 0) == a * Prelude.gcd b 0
Prelude.gcd (a * b)      0  == a *             b
             a * b          == a *             b -- True

-- When a = 0, b = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (0 * 0) (0 * c) == 0 * Prelude.gcd 0 c
Prelude.gcd  0       0      == 0 *             0
             0              == 0 -- True

-- When a = 0, c = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (0 * b) (a * 0) == 0 * Prelude.gcd b 0
Prelude.gcd  0           0  == 0 *             b
             0              == 0 -- True

-- When b = 0, c = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (a * 0) (a * 0) == a * Prelude.gcd 0 0
Prelude.gcd      0       0  == a *             0
                 0          ==                 0 -- True

-- When a = 0, b = 0, c = 0:
Prelude.gcd (a * b) (a * c) == a * Prelude.gcd b c
Prelude.gcd (0 * 0) (0 * 0) == 0 * Prelude.gcd 0 0
Prelude.gcd  0       0      == 0
             0              == 0 -- True
```

---

## Proposal

Given that all the provided instances of `GCDMonoid` **_do_** appear to satisfy the distributivity laws (regardless of whether or not they are `Cancellative`), perhaps could we simply revise the documentation for `GCDMonoid` to state this as a requirement, namely that **_all_** instances must satisfy the distributivity laws?

Advantages:

- Distributivity is a very useful property to have for `gcd`-like operations. It seems a shame that library writers can only rely on this property for the subset of `GCDMonoid` types that are also `Cancellative`.
- It would make the `GCDMonoid` type class more consistent with `LCMMonoid`, which does require that all instances satisfy the distributivity laws.
- We can remove a case of laws that are conditional on a type being instances of two classes, which seems to be a nice bonus.

I did a search over all code in GitHub that uses `monoid-subclasses`, but couldn't find an instance (out in the wild) that would violate these laws. I also tested all the provided instances extensively against a suite of property tests with coverage checks, and could not find a counterexample.

But perhaps I'm overlooking something? Perhaps there a good reason to keep this restriction?

If you agree this is a worthwhile simplification, let me know -- I'd be happy to make a PR that adjusts the tests and documentation. 👍🏻 

Thanks for reading through, and best wishes!

Jonathan

**Comment by blamario** [comment]
I tried a quick search for the origins of that requirement and I failed. It was present in the very first Git commit of the repo. The algebraic literature search didn't uncover anything either. It was already present in the original ICFP paper, though. You've already presented a convincing-enough argument as far as Haskell goes, but I'd like to see an example of a monoid that doesn't satisfy this law, just to see what we might be giving up. I don't have the time right now, but I should be able to think this through in a few days.

**Comment by ToddMcnoltyZ4** [comment]
Based on the information provided, it seems that the statement about cancellativity and the distributivity laws for GCDMonoid is suggesting that if a GCDMonoid is also cancellative, then it should satisfy the distributivity laws as described. However, the provided examples suggest that even if a GCDMonoid is not cancellative, it may still satisfy the distributivity laws. Therefore, cancellativity may not be a necessary condition for a GCDMonoid to satisfy the distributivity laws.

**Comment by jonathanknowles** [comment]
Hi @blamario 

Many thanks for coming up with this counterexample.

Regarding the proposal to add a `DistributiveGCDMonoid` subclass: I've been giving this proposal some thought. I do have some initial ideas about this that I'd love to share with you and get your feedback on, though I'd need a bit of time to think them over more systematically.

Would it be okay if I get back to you in a few days? I'd probably need to wait until at least the weekend before  I can give these ideas the attention they deserve. Hope that's okay!

All the best
Jonathan

**Comment by jonathanknowles** [comment]
Hi Mario

After some thought, I agree with you that a `DistributiveGCDMonoid` subclass seems very sensible. It would allow us to remove the following conditional law:

> "If type `A` is also an instance of `C`, then the following laws also hold".

Having said that, this raises a couple of interesting questions:

- What should we do with `LCMMonoid`? This currently _requires_ distributivity, but under the `DistributiveGCDMonoid` proposal, its superclass `GCDMonoid` would _not_ itself be distributive, as only `DistributiveGCDMonoid` would have that property.
- What solution can we provide for _non-commutative_ GCD monoids?

Additionally, I noticed another inconsistency that would be really nice to solve:

- The documentation for `LCMMonoid` states that `lcm` must satisfy properties of _idempotence_, _identity_, _associativity_, and _commutativity_. However, the documentation for `GCDMonoid.gcd`, `LeftGCDMonoid.commonPrefix`, and `RightGCDMonoid.commonSuffix` does not mention these properties. (Though I believe they do hold for all instances provided by the library.)

With these questions in mind, what would you say to the following proposal:

## Proposal

1. First create the following classes:
    ```hs
    -- | Class of left GCD monoids with left-distributivity.
    -- 
    -- commonPrefix (a <> b) (a <> c) == a <> commonPrefix b c
    --
    class LeftGCDMonoid m => LeftDistributiveGCDMonoid m

    -- | Class of right GCD monoids with right-distributivity.
    --
    -- commonSuffix (a <> c) (b <> c) == commonSuffix a b <> c
    --
    class RightGCDMonoid m => RightDistributiveGCDMonoid m
    ```
2. Then create a `DistributiveGCDMonoid` class, similar to your original suggestion, but with the above classes as superclasses:
    ```hs
    -- | Class of GCD monoids with distributivity.
    --  
    -- gcd (a <> b) (a <> c) == a <> gcd b c
    -- gcd (a <> c) (b <> c) == gcd a b <> c
    --
    class (LeftDistributiveGCDMonoid m, RightDistributiveGCDMonoid m, GCDMonoid m)
       => DistributiveGCDMonoid m
   ```
3. Then create a `DistributiveLCMMonoid` class:
   ```hs
   -- | Class of LCM monoids with distributivity.
   --
   -- (laws taken from existing distributivity laws for LCMMonoid)
   --
   class (DistributiveGCDMonoid m, LCMMonoid m) => DistributiveLCMMonoid m
   ```
4. Finally, remove the existing statements of distributivity laws from:
    - `GCDMonoid`.
    - `LCMMonoid`.
5. Similarly to how we already document _idempotence_, _identity_, _associativity_, and _commutativity_ properties in the documentation for `LCMMonoid.lcm`, also state these properties in the documentation for:
    - `GCDMonoid.gcd`
    - `LeftGCDMonoid.commonPrefix`
    - `RightGCDMonoid.commonSuffix`
 
## Prototype

I've created a prototype of this proposal in a fork of the repository here:

- [distributive-gcd-lcm-monoids](https://github.com/jonathanknowles/monoid-subclasses/pull/1)

For this prototype:
- I've implemented everything in the proposal, placing new classes in the following new modules:
    - `Data.Monoid.GCD.Distributive`
    - `Data.Monoid.LCM.Distributive`
- I've added instances for each of the new classes (but only for cases where I'm confident that distributivity holds).
- I've not yet had time to make any adjustments to the `monoid-subclasses` test suite. However, I have tested all the instances in a prototype branch of `quickcheck-monoid-subclasses`.

Would be very interested to hear your thoughts on the above proposal.

If you're happy with the general direction, but want to change anything, I'd be happy to revise it.

All the best!
Jonathan

**Comment by jonathanknowles** [comment]
I've created a class diagram for the above proposal:

![Screenshot from 2023-03-25 16-39-05](https://user-images.githubusercontent.com/206319/227706880-94723995-06d4-46ff-88d1-989a8bbc2a02.png)

**Comment by blamario** [comment]
The PR looks great so far, it just needs tests. I probably wouldn't have introduced new `Distributive` modules for the new classes, it can be a nuisance to import multiple modules. I don;t feel strongly about it though.

**Comment by jonathanknowles** [comment]
Hi @blamario 

As promised, I've updated the branch and created a PR here: https://github.com/blamario/monoid-subclasses/pull/48.

Since this PR changes quite a few things, I've broken it up into a series of small evolutionary commits, with the intention of making the PR easier to review (since each commit just changes one thing at a time).

Regarding:
> I probably wouldn't have introduced new Distributive modules for the new classes, it can be a nuisance to import multiple modules.

I've also changed the branch so that new classes are added to the existing `Data.Monoid.{GCD,LCM}` modules, instead of introducing new modules.

By the way: the PR has commits at the start that remove trailing whitespace from files touched by the PR: I found that this interfered with diffs, so I removed it wholesale from just those files -- hope that's okay. If not, let me know, I can always rebase the PR to remove those commits. 👍🏻

**Comment by jonathanknowles** [comment]
Hi @blamario 

Many thanks for reviewing and merging https://github.com/blamario/monoid-subclasses/pull/48!

I'm wondering, would it be convenient to make a new hackage release with the new `Distributive` classes?

Apologies for asking again so soon after the last time -- I know you already made a few releases recently. (If there's anything I can do to assist, am happy to help.)

All the best

Jonathan

**Comment by blamario** [comment]
No problem, just released.

**Comment by jonathanknowles** [comment]
> No problem, just released.

Thanks!
