### ISSUE TITLE
git tree lacks some files

### ISSUE THREAD

**Issue by trofi** [blamario/monoid-subclasses#7]
Tried to chase testsuite
```
  Textual.foldl:                FAIL (0.02s)
    *** Failed! (after 23 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "[\[237]g\[159]\[253]x]\[139]\28\[191,134]|"
    Use --quickcheck-replay '22 TFGenR 0000000807931105000000000007A120000000000000DF8400000002540BE400 0 36028792723996672 55 0' to reproduce.
```
but it seems that git tree lacks some files:
```
Configuring monoid-subclasses-0.4.1.1...
Building monoid-subclasses-0.4.1.1...
Preprocessing library monoid-subclasses-0.4.1.1...
Setup: can't find source for Data/Monoid/Instances/Markup in .,
dist/build/autogen
```

**Comment by blamario** [comment]
Thank you, that was an accidental commit of a module that's not ready for release. I've removed it from the package for the time being.

**Comment by blamario** [comment]
As for the testsuite failure... I guess QuickCheck is not as reproducible as I thought:

$ ./dist/build/Main/Main --quickcheck-replay '22 TFGenR 0000000807931105000000000007A120000000000000DF8400000002540BE400 0 36028792723996672 55 0' -p Textual.foldl
MonoidSubclasses
  Textual.foldl:   OK (0.42s)
    +++ OK, passed 100 tests.
  Textual.foldl':  OK (0.40s)
    +++ OK, passed 100 tests.
  Textual.foldl_:  OK (0.32s)
    +++ OK, passed 100 tests.
  Textual.foldl_': OK (0.32s)

What is your platform and compiler version? Also, which version of bytestring package do you have installed?

**Comment by trofi** [comment]
Retried once again and found out that -O0 case fails, while -O2 works.
(I usually build stuff as -O0 first to make sure packages pass basic build test.)

Full log (all library/compiler versions):

 * Package:    dev-haskell/monoid-subclasses-0.4.1.1
 * Repository: haskell
 * Maintainer: haskell
 * USE:        abi_x86_64 amd64 doc elibc_glibc hscolour kernel_linux test userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug test userpriv usersandbox
 * Package:    dev-haskell/monoid-subclasses-0.4.1.1
 * Repository: haskell
 * Maintainer: haskell
 * USE:        abi_x86_64 amd64 doc elibc_glibc hscolour kernel_linux test userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug test userpriv usersandbox
>>> Unpacking source...
>>> Unpacking monoid-subclasses-0.4.1.1.tar.gz to /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work
>>> Source unpacked in /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work
/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1 /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work
Initialized empty Git repository in /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1/.git/
[master (root-commit) b532b26] state after src_unpack()
 14 files changed, 5004 insertions(+)
 create mode 100644 BSD3-LICENSE.txt
 create mode 100644 Data/Monoid/Cancellative.hs
 create mode 100644 Data/Monoid/Factorial.hs
 create mode 100644 Data/Monoid/Instances/ByteString/UTF8.hs
 create mode 100644 Data/Monoid/Instances/Concat.hs
 create mode 100644 Data/Monoid/Instances/Markup.hs
 create mode 100644 Data/Monoid/Instances/Measured.hs
 create mode 100644 Data/Monoid/Instances/Positioned.hs
 create mode 100644 Data/Monoid/Instances/Stateful.hs
 create mode 100644 Data/Monoid/Null.hs
 create mode 100644 Data/Monoid/Textual.hs
 create mode 100644 Setup.lhs
 create mode 100644 Test/TestMonoidSubclasses.hs
 create mode 100644 monoid-subclasses.cabal
/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work
>>> Preparing source in /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1 ...
>>> Source prepared.
/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1 /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1
On branch master
nothing to commit, working directory clean
/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1
>>> Configuring source in /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1 ...
 * Using cabal-1.22.4.0.
 * Prepending /usr/lib64/ghc-7.10.1 to LD_LIBRARY_PATH
/usr/bin/ghc -package Cabal-1.22.4.0 --make /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1/Setup.lhs -O0 -O0 -O0 -dynamic -o setup
[1 of 1] Compiling Main             ( /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1/Setup.lhs, /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1/Setup.o )
Linking setup ...
./setup configure --ghc --prefix=/usr --with-compiler=/usr/bin/ghc --with-hc-pkg=/usr/bin/ghc-pkg --prefix=/usr --libdir=/usr/lib64 --libsubdir=monoid-subclasses-0.4.1.1/ghc-7.10.1 --datadir=/usr/share/ --datasubdir=monoid-subclasses-0.4.1.1/ghc-7.10.1 --with-haddock=/usr/bin/haddock-ghc-7.10.1 --enable-tests --ghc-option=-O0 --ghc-option=-O0 --ghc-option=-O0 --ghc-option=-j4 --ghc-option=-optc-march=corei7-avx --ghc-option=-optc-mtune=corei7-avx --ghc-option=-optc-mcx16 --ghc-option=-optc-msahf --ghc-option=-optc-maes --ghc-option=-optc-mpclmul --ghc-option=-optc-mpopcnt --ghc-option=-optc-mavx --ghc-option=-optc-msse4.2 --ghc-option=-optc-msse4.1 --ghc-option=-optc--param=l1-cache-size=32 --ghc-option=-optc--param=l1-cache-line-size=64 --ghc-option=-optc--param=l2-cache-size=8192 --ghc-option=-optc-O2 --ghc-option=-optc-pipe --ghc-option=-optc-fdiagnostics-show-option --ghc-option=-optc-frecord-gcc-switches --ghc-option=-optl-Wl,-O1 --ghc-option=-optl-Wl,--as-needed --ghc-option=-optl-Wl,--hash-style=gnu --disable-executable-stripping --docdir=/usr/share/doc/monoid-subclasses-0.4.1.1 --verbose --enable-shared --enable-executable-dynamic --sysconfdir=/etc --disable-library-stripping
Configuring monoid-subclasses-0.4.1.1...
Dependency QuickCheck ==2.*: using QuickCheck-2.8.1
Dependency base >=4.5 && <5: using base-4.8.0.0
Dependency bytestring >=0.9 && <1.0: using bytestring-0.10.6.0
Dependency containers >=0.5.2.0 && <0.6: using containers-0.5.6.2
Dependency monoid-subclasses -any: using monoid-subclasses-0.4.1.1
Dependency primes ==0.2.*: using primes-0.2.1.0
Dependency quickcheck-instances ==0.3.*: using quickcheck-instances-0.3.11
Dependency tasty >=0.7: using tasty-0.10.1.2
Dependency tasty-quickcheck >=0.7: using tasty-quickcheck-0.8.3.2
Dependency text >=0.11 && <1.3: using text-1.2.1.1
Dependency vector >=0.9 && <0.12: using vector-0.10.12.3
Using Cabal-1.22.4.0 compiled by ghc-7.10
Using compiler: ghc-7.10.1
Using install prefix: /usr
Binaries installed in: /usr/bin
Libraries installed in: /usr/lib64/monoid-subclasses-0.4.1.1/ghc-7.10.1
Private binaries installed in: /usr/libexec
Data files installed in: /usr/share/monoid-subclasses-0.4.1.1/ghc-7.10.1
Documentation installed in: /usr/share/doc/monoid-subclasses-0.4.1.1
Configuration files installed in: /etc
Using alex version 3.1.4 found on system at: /usr/bin/alex
Using ar found on system at: /usr/bin/ar
Using c2hs version 0.25.2 found on system at: /usr/bin/c2hs
Using cpphs version 1.19 found on system at: /usr/bin/cpphs
Using gcc version 5.1.0 found on system at: /usr/bin/gcc
Using ghc version 7.10.1 given by user at: /usr/bin/ghc
Using ghc-pkg version 7.10.1 given by user at: /usr/bin/ghc-pkg
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.16.0 given by user at: /usr/bin/haddock-ghc-7.10.1
Using happy version 1.19.5 found on system at: /usr/bin/happy
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at: /usr/bin/hpc
Using hsc2hs version 0.67 found on system at: /usr/bin/hsc2hs
Using hscolour version 1.22 found on system at: /usr/bin/HsColour
Using jhc version 0.8.2 found on system at: /usr/bin/jhc
Using ld found on system at: /usr/bin/ld
No lhc found
No lhc-pkg found
Using pkg-config version 0.28 found on system at: /usr/bin/pkg-config
Using strip version 2.25 found on system at: /usr/bin/strip
Using tar found on system at: /bin/tar
Using uhc version 1.1.9.1 found on system at: /usr/bin/uhc
>>> Source configured.
>>> Compiling source in /tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1 ...
./setup build
Building monoid-subclasses-0.4.1.1...
Preprocessing library monoid-subclasses-0.4.1.1...
[ 1 of 10] Compiling Data.Monoid.Null ( Data/Monoid/Null.hs, dist/build/Data/Monoid/Null.o )
[ 2 of 10] Compiling Data.Monoid.Factorial ( Data/Monoid/Factorial.hs, dist/build/Data/Monoid/Factorial.o )
[ 3 of 10] Compiling Data.Monoid.Cancellative ( Data/Monoid/Cancellative.hs, dist/build/Data/Monoid/Cancellative.o )
[ 4 of 10] Compiling Data.Monoid.Textual ( Data/Monoid/Textual.hs, dist/build/Data/Monoid/Textual.o )

Data/Monoid/Textual.hs:483:10: Warning:
    Orphan instance: instance IsString (Sequence.Seq Char)
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.

Data/Monoid/Textual.hs:553:10: Warning:
    Orphan instance: instance IsString (Vector.Vector Char)
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.
[ 5 of 10] Compiling Data.Monoid.Instances.ByteString.UTF8 ( Data/Monoid/Instances/ByteString/UTF8.hs, dist/build/Data/Monoid/Instances/ByteString/UTF8.o )
[ 6 of 10] Compiling Data.Monoid.Instances.Concat ( Data/Monoid/Instances/Concat.hs, dist/build/Data/Monoid/Instances/Concat.o )
[ 7 of 10] Compiling Data.Monoid.Instances.Markup ( Data/Monoid/Instances/Markup.hs, dist/build/Data/Monoid/Instances/Markup.o )

Data/Monoid/Instances/Markup.hs:17:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()

Data/Monoid/Instances/Markup.hs:23:1: Warning:
    The import of ‘Data.Tree’ is redundant
      except perhaps to import instances from ‘Data.Tree’
    To import instances alone, use: import Data.Tree()

Data/Monoid/Instances/Markup.hs:24:1: Warning:
    The qualified import of ‘Data.Tree’ is redundant
      except perhaps to import instances from ‘Data.Tree’
    To import instances alone, use: import Data.Tree()
[ 8 of 10] Compiling Data.Monoid.Instances.Measured ( Data/Monoid/Instances/Measured.hs, dist/build/Data/Monoid/Instances/Measured.o )
[ 9 of 10] Compiling Data.Monoid.Instances.Positioned ( Data/Monoid/Instances/Positioned.hs, dist/build/Data/Monoid/Instances/Positioned.o )
[10 of 10] Compiling Data.Monoid.Instances.Stateful ( Data/Monoid/Instances/Stateful.hs, dist/build/Data/Monoid/Instances/Stateful.o )
In-place registering monoid-subclasses-0.4.1.1...
Preprocessing test suite 'Main' for monoid-subclasses-0.4.1.1...
[ 1 of 10] Compiling Data.Monoid.Cancellative ( Data/Monoid/Cancellative.hs, dist/build/Main/Main-tmp/Data/Monoid/Cancellative.dyn_o )
[ 2 of 10] Compiling Data.Monoid.Null ( Data/Monoid/Null.hs, dist/build/Main/Main-tmp/Data/Monoid/Null.dyn_o )
[ 3 of 10] Compiling Data.Monoid.Factorial ( Data/Monoid/Factorial.hs, dist/build/Main/Main-tmp/Data/Monoid/Factorial.dyn_o )
[ 4 of 10] Compiling Data.Monoid.Textual ( Data/Monoid/Textual.hs, dist/build/Main/Main-tmp/Data/Monoid/Textual.dyn_o )
[ 5 of 10] Compiling Data.Monoid.Instances.Positioned ( Data/Monoid/Instances/Positioned.hs, dist/build/Main/Main-tmp/Data/Monoid/Instances/Positioned.dyn_o )
[ 6 of 10] Compiling Data.Monoid.Instances.Stateful ( Data/Monoid/Instances/Stateful.hs, dist/build/Main/Main-tmp/Data/Monoid/Instances/Stateful.dyn_o )
[ 7 of 10] Compiling Data.Monoid.Instances.Measured ( Data/Monoid/Instances/Measured.hs, dist/build/Main/Main-tmp/Data/Monoid/Instances/Measured.dyn_o )
[ 8 of 10] Compiling Data.Monoid.Instances.Concat ( Data/Monoid/Instances/Concat.hs, dist/build/Main/Main-tmp/Data/Monoid/Instances/Concat.dyn_o )
[ 9 of 10] Compiling Data.Monoid.Instances.ByteString.UTF8 ( Data/Monoid/Instances/ByteString/UTF8.hs, dist/build/Main/Main-tmp/Data/Monoid/Instances/ByteString/UTF8.dyn_o )
[10 of 10] Compiling Main             ( Test/TestMonoidSubclasses.hs, dist/build/Main/Main-tmp/Main.dyn_o )
Linking dist/build/Main/Main ...
./setup haddock --hyperlink-source
Running Haddock for monoid-subclasses-0.4.1.1...
Running hscolour for monoid-subclasses-0.4.1.1...
Preprocessing library monoid-subclasses-0.4.1.1...
Preprocessing test suite 'Main' for monoid-subclasses-0.4.1.1...
Preprocessing library monoid-subclasses-0.4.1.1...
Haddock coverage:
 100% (  3 /  3) in 'Data.Monoid.Null'
 100% (  7 /  7) in 'Data.Monoid.Factorial'
 100% ( 13 / 13) in 'Data.Monoid.Cancellative'

Data/Monoid/Textual.hs:483:10: Warning:
    Orphan instance: instance IsString (Sequence.Seq Char)
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.

Data/Monoid/Textual.hs:553:10: Warning:
    Orphan instance: instance IsString (Vector.Vector Char)
    To avoid this
        move the instance declaration to the module of the class or of the type, or
        wrap the type with a newtype and declare the instance on the new type.
 100% (  2 /  2) in 'Data.Monoid.Textual'
  67% (  2 /  3) in 'Data.Monoid.Instances.ByteString.UTF8'
  Missing documentation for:
    ByteStringUTF8 (Data/Monoid/Instances/ByteString/UTF8.hs:67)
  50% (  2 /  4) in 'Data.Monoid.Instances.Concat'
  Missing documentation for:
    concatenate (Data/Monoid/Instances/Concat.hs:43)
    extract (Data/Monoid/Instances/Concat.hs:41)

Data/Monoid/Instances/Markup.hs:17:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()

Data/Monoid/Instances/Markup.hs:23:1: Warning:
    The import of ‘Data.Tree’ is redundant
      except perhaps to import instances from ‘Data.Tree’
    To import instances alone, use: import Data.Tree()

Data/Monoid/Instances/Markup.hs:24:1: Warning:
    The qualified import of ‘Data.Tree’ is redundant
      except perhaps to import instances from ‘Data.Tree’
    To import instances alone, use: import Data.Tree()
  25% (  1 /  4) in 'Data.Monoid.Instances.Markup'
  Missing documentation for:
    TagSoup (Data/Monoid/Instances/Markup.hs:39)
    soupLeaf (Data/Monoid/Instances/Markup.hs:284)
    soupTag (Data/Monoid/Instances/Markup.hs:288)
  75% (  3 /  4) in 'Data.Monoid.Instances.Measured'
  Missing documentation for:
    extract (Data/Monoid/Instances/Measured.hs:36)
  43% (  3 /  7) in 'Data.Monoid.Instances.Positioned'
  Missing documentation for:
    OffsetPositioned (Data/Monoid/Instances/Positioned.hs:47)
    LinePositioned (Data/Monoid/Instances/Positioned.hs:51)
    extract (Data/Monoid/Instances/Positioned.hs:44)
    position (Data/Monoid/Instances/Positioned.hs:45)
  40% (  2 /  5) in 'Data.Monoid.Instances.Stateful'
  Missing documentation for:
    extract (Data/Monoid/Instances/Stateful.hs:42)
    state (Data/Monoid/Instances/Stateful.hs:45)
    setState (Data/Monoid/Instances/Stateful.hs:48)
Warning: Data.Monoid.Instances.Positioned: could not find link destinations for:
    Positioned
Documentation created: dist/doc/html/monoid-subclasses/index.html
Preprocessing test suite 'Main' for monoid-subclasses-0.4.1.1...
>>> Source compiled.
>>> Test phase: dev-haskell/monoid-subclasses-0.4.1.1
 * >>> Test phase [cabal test]: dev-haskell/monoid-subclasses-0.4.1.1
./setup test
Running 1 test suites...
Test suite Main: RUNNING...
MonoidSubclasses
  CommutativeMonoid:            OK (0.01s)
    +++ OK, passed 100 tests.
  MonoidNull:                   OK (1.19s)
    +++ OK, passed 100 tests.
  PositiveMonoid:               OK (0.35s)
    +++ OK, passed 100 tests.
  mconcat . factors == id:      OK (2.85s)
    +++ OK, passed 100 tests.
  all factors . factors:        OK (2.07s)
    +++ OK, passed 100 tests.
  splitPrimePrefix:             OK (2.11s)
    +++ OK, passed 100 tests.
  splitPrimeSuffix:             OK (3.37s)
    +++ OK, passed 100 tests.
  primePrefix:                  OK (0.56s)
    +++ OK, passed 100 tests.
  primeSuffix:                  OK (0.65s)
    +++ OK, passed 100 tests.
  inits:                        OK (0.77s)
    +++ OK, passed 100 tests.
  tails:                        OK (0.49s)
    +++ OK, passed 100 tests.
  foldl:                        OK (2.06s)
    +++ OK, passed 100 tests.
  foldl':                       OK (2.04s)
    +++ OK, passed 100 tests.
  foldr:                        OK (1.84s)
    +++ OK, passed 100 tests.
  length:                       OK (0.73s)
    +++ OK, passed 100 tests.
  span:                         OK (2.07s)
    +++ OK, passed 100 tests.
  spanMaybe:                    OK (1.40s)
    +++ OK, passed 100 tests.
  split:                        OK (11.25s)
    +++ OK, passed 100 tests.
  splitAt:                      OK (1.82s)
    +++ OK, passed 100 tests.
  reverse:                      OK (1.83s)
    +++ OK, passed 100 tests.
  stable:                       OK (0.93s)
    +++ OK, passed 100 tests.
  fromText:                     OK (0.09s)
    +++ OK, passed 100 tests.
  singleton:                    OK
    +++ OK, passed 100 tests.
  Textual.splitCharacterPrefix: OK (0.15s)
    +++ OK, passed 100 tests.
  Textual.characterPrefix:      OK (0.05s)
    +++ OK, passed 100 tests.
  Textual factors:              OK (0.12s)
    +++ OK, passed 100 tests.
  Textual.unfoldr:              OK (0.15s)
    +++ OK, passed 100 tests.
  factors . fromString:         OK (0.11s)
    +++ OK, passed 100 tests.
  Textual.map:                  OK (0.25s)
    +++ OK, passed 100 tests.
  Textual.concatMap:            OK (0.40s)
    +++ OK, passed 100 tests.
  Textual.any:                  OK (0.05s)
    +++ OK, passed 100 tests.
  Textual.all:                  OK (0.04s)
    +++ OK, passed 100 tests.
  Textual.foldl:                FAIL (0.02s)
    *** Failed! (after 22 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "\[148]\25L\[174,169]\[243]\[245].\[249]<\[206] \[230]\[224]_\[187]\8"
    Use --quickcheck-replay '21 TFGenR 0000000BB36AE58D00000000000F4240000000000000DF850000000218711A00 0 18014394214514688 54 0' to reproduce.
  Textual.foldr:                OK (0.29s)
    +++ OK, passed 100 tests.
  Textual.foldl':               FAIL
    *** Failed! (after 21 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:381:3-8: Assertion failed
    "F`\[161]@\[169,159,134]r6\[195]\12O\[133]\27"
    Use --quickcheck-replay '20 TFGenR 0000000BB36AE58D00000000000F4240000000000000DF850000000218711A00 0 36028779839094784 55 0' to reproduce.
  Textual.scanl:                FAIL (0.04s)
    *** Failed! (after 27 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:381:3-8: Assertion failed
    "\[152]-6\[151]\22\[165,157,166]Qߍ\[244]갡$\[218,134,183]\[225]"
    Use --quickcheck-replay '26 TFGenR 0000000BB36AE58D00000000000F4240000000000000DF850000000218711A00 0 4611685984067649536 62 0' to reproduce.
  Textual.scanr:                OK (0.42s)
    +++ OK, passed 100 tests.
  Textual.scanl1:               FAIL (0.01s)
    *** Failed! (after 21 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "\[148]T_\[159,139]i\30\[178]\4\[227]"
    Use --quickcheck-replay '20 TFGenR 0000000BB36AE58D00000000000F4240000000000000DF850000000218711A00 0 288230238712758272 58 0' to reproduce.
  Textual.scanr1:               OK (0.22s)
    +++ OK, passed 100 tests.
  Textual.toString:             OK (0.44s)
    +++ OK, passed 100 tests.
  Textual.mapAccumL:            FAIL (0.02s)
    *** Failed! (after 21 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "\[181,167]#\[204]\27\[219]"
    Use --quickcheck-replay '20 TFGenR 0000000BB36AE58D00000000000F4240000000000000DF850000000218711A00 0 2305841909702066176 61 0' to reproduce.
  Textual.mapAccumR:            OK (0.27s)
    +++ OK, passed 100 tests.
  Textual.takeWhile:            OK (0.20s)
    +++ OK, passed 100 tests.
  Textual.dropWhile:            OK (0.28s)
    +++ OK, passed 100 tests.
  Textual.span:                 OK (0.10s)
    +++ OK, passed 100 tests.
  Textual.break:                OK (0.11s)
    +++ OK, passed 100 tests.
  Textual.spanMaybe:            FAIL (0.05s)
    *** Failed! (after 46 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    (<function>,<function>,False)
    "@\[161,181]\3W\[218]\[253]B]\[129]} xZ\[158]\0\0\[155]\[209]T:\[232,143,175,187]\[215,149,141]DZ=\[233]_;T\[131]`3g\[131,135]s"
    Use --quickcheck-replay '45 TFGenR AE36DD80E3C7C7FE5F9BAC32438F60E94756DD5241369F36E320E621D60610AB 0 268435455 28 0' to reproduce.
  Textual.split:                OK (0.24s)
    +++ OK, passed 100 tests.
  Textual.find:                 OK (0.13s)
    +++ OK, passed 100 tests.
  Textual.foldl_:               FAIL (0.02s)
    *** Failed! (after 23 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "\[198].<\[180,188]p.p\[202,175,179]P\[172]\[233]\3' v:"
    Use --quickcheck-replay '22 TFGenR DE79F5150E23270CDDA09007D29F833B70CF80420C43B6228B7C3F6EB25CC9D9 0 255 8 0' to reproduce.
  Textual.foldr_:               OK (0.25s)
    +++ OK, passed 100 tests.
  Textual.foldl_':              FAIL (0.02s)
    *** Failed! (after 22 tests): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    "\[217]]a\[222]\[201]j\[154,129]"
    Use --quickcheck-replay '21 TFGenR 7C6185310FC89D2FFE32F1B432ACC7A770082FC0A1D70C6BF0F48D88C99A0DAF 0 511 9 0' to reproduce.
  Textual.span_:                OK (0.12s)
    +++ OK, passed 100 tests.
  Textual.break_:               OK (0.10s)
    +++ OK, passed 100 tests.
  Textual.spanMaybe_:           FAIL (0.02s)
    *** Failed! (after 22 tests and 1 shrink): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    (<function>,False)
    "\[129,190]-\[217]\[252]4\[175]H\[150]="
    Use --quickcheck-replay '21 TFGenR 01F7D4B898240D0A3470762ECF09BD997A404D014FF6DCA3477BB8BA30AF975F 0 4095 12 0' to reproduce.
  Textual.spanMaybe_':          FAIL (0.02s)
    *** Failed! (after 22 tests and 1 shrink): 
    Exception:
      Data/Monoid/Instances/ByteString/UTF8.hs:376:3-8: Assertion failed
    (<function>,False)
    "\[178,180]!\18\[129]"
    Use --quickcheck-replay '21 TFGenR 359143DF6524F9BEF926A3D0EB23E709297A9513795022550134D7057298B2B3 0 8191 13 0' to reproduce.
  Textual.takeWhile_:           OK (0.19s)
    +++ OK, passed 100 tests.
  Textual.dropWhile_:           OK (0.30s)
    +++ OK, passed 100 tests.
  stripPrefix:                  OK (0.96s)
    +++ OK, passed 100 tests.
  isPrefixOf:                   OK (0.92s)
    +++ OK, passed 100 tests.
  stripSuffix:                  OK (0.98s)
    +++ OK, passed 100 tests.
  isSuffixOf:                   OK (0.90s)
    +++ OK, passed 100 tests.
  </>:                          OK
    +++ OK, passed 100 tests.
  cancellative stripPrefix:     OK (0.04s)
    +++ OK, passed 100 tests.
  cancellative stripSuffix:     OK (0.03s)
    +++ OK, passed 100 tests.
  cancellative </>:             OK
    +++ OK, passed 100 tests.
  stripCommonPrefix 1:          OK (1.43s)
    +++ OK, passed 100 tests.
  stripCommonPrefix 2:          OK (1.47s)
    +++ OK, passed 100 tests.
  stripCommonSuffix 1:          OK (0.68s)
    +++ OK, passed 100 tests.
  stripCommonSuffix 2:          OK (0.64s)
    +++ OK, passed 100 tests.
  gcd:                          OK (0.02s)
    +++ OK, passed 100 tests.
  cancellative gcd:             OK
    +++ OK, passed 100 tests.

10 out of 72 tests failed (53.97s)
Test suite Main: FAIL
Test suite logged to: dist/test/monoid-subclasses-0.4.1.1-Main.log
0 of 1 test suites (0 of 1 test cases) passed.
 * ERROR: dev-haskell/monoid-subclasses-0.4.1.1::haskell failed (test phase):
 *   cabal test failed
 * 
 * Call stack:
 *     ebuild.sh, line   90:  Called src_test
 *   environment, line 2862:  Called haskell-cabal_src_test
 *   environment, line 1978:  Called die
 * The specific snippet of code:
 *           ./setup "$@" || die "cabal test failed";
 * 
 * If you need support, post the output of `emerge --info '=dev-haskell/monoid-subclasses-0.4.1.1::haskell'`,
 * the complete build log and the output of `emerge -pqv '=dev-haskell/monoid-subclasses-0.4.1.1::haskell'`.
 * The complete build log is located at '/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/temp/environment'.
 * Working directory: '/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1'
 * S: '/tmp/portage/dev-haskell/monoid-subclasses-0.4.1.1/work/monoid-subclasses-0.4.1.1'

**Comment by blamario** [comment]
That's one thorough report!

The reason -O0 was needed to trigger the failure was because there were a couple of overoptimistic assertions, which get turned off by optimizations. I've fixed them now.

Thank you again.
